spring:
  h2:
    console:
      enabled:  true

  datasource:
    url:  jdbc:h2:~/test;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    show-sql: true

  properties:
    hibernate:
      format_sql: true



handlebars:
  suffix: .html
  cache:  false
  expose-session-attributes:  true



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder:  TRACE


server:
  servlet:
    session:
      tracking-modes: cookie